#!/bin/sh

MINECRAFT_SERVER_NAME=minecraft-server
MINECRAFT_MAX_PLAYERS=10
MINECRAFT_DIFFICULTY=NORMAL
MINECRAFT_PVP=FALSE

docker run -d \
    -p 25565:25565 \
    --name $MINECRAFT_SERVER_NAME \
    -e MEMORY="1G" \
    -e EULA=TRUE \
    -e VERSION=LATEST \
    -e DIFFICULTY=$MINECRAFT_DIFFICULTY \
    -e MAX_PLAYERS=$MINECRAFT_MAX_PLAYERS \
    -e ENABLE_COMMAND_BLOCK=TRUE \
    -e PVP=$MINECRAFT_PVP \
    -v $MINECRAFT_SERVER_NAME-data:/data \
    itzg/minecraft-server

